### ISSUE TITLE
The IDE using to developing

### ISSUE THREAD

**Issue by mateusz-piotrowski** [Banogrono/AVCalculator#1]
In files in the repository you have the following path: `.idea/.idea.AVCalculator/.idea`
The main programming language which you use is **C#**, but are you writing in the **IntelliJ IDEA**?

**Comment by Banogrono** [comment]
Not exactly. I'm using the Jetbrains's Rider IDE which is based on IntelliJ platform - I highly recommend it: https://www.jetbrains.com/rider/

**Comment by mateusz-piotrowski** [comment]
Okay,  but in which areas **Rider** is better than **Visual Studio**?
Did you buy a personal license?

**Comment by Banogrono** [comment]
I don’t know if it’s better, all I know is that it fits **my** needs better than Visual Studio. Which basically comes to Rider being cross-platform (I work on both Linux and Windows machines) and lightweight (~3GB vs ~20GB). Also I like Rider’s styling more and the fact that it’s less *“microsofty”*.

**Comment by mateusz-piotrowski** [comment]
Okey - it appeals to me. How about license? You using free trial or bought
the one?

**Comment by Banogrono** [comment]
I think you're replying to message before I edited it; but basically it's just like I said:

> I got the student's license - It comes with all JetBrains products, including DataGrip - you might want to check it out. ;] 

The student's license is free, and valid for a year, then you can extend it for another year providing that you have a student status.
