### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Darkvod** [Banogrono/AVCalculator#3]
When I press the 'M+' button when there is no number on the calculator screen or the number is 0 the calculator stops working and an 'unhandled exception' error appears.
Ex:.
```
The thread 0xcf0 has exited with code 0 (0x0).
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
An unhandled exception of type 'System.FormatException' occurred in System.Private.CoreLib.dll
Input string was not in a correct format.
```

Also, There is no information when I try to divide a value by 0, I think the calculator should warn us that this operation is illegal.

**Comment by Banogrono** [comment]
Workin' on it m8

**Comment by Banogrono** [comment]
fixed
